FROM ruby:3.4.5-slim

ENV TZ=America/Sao_Paulo
ENV INSTALL_PATH=/app
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    libyaml-dev \
    imagemagick \
    tzdata \
    curl \
    nano \
    git \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd -g $GROUP_ID appuser && \
    useradd -u $USER_ID -g appuser -m -s /bin/bash appuser

WORKDIR $INSTALL_PATH

RUN chown -R appuser:appuser $INSTALL_PATH

ENV BUNDLE_PATH=/usr/local/bundle

COPY --chown=appuser:appuser Gemfile Gemfile.lock ./
RUN bundle install

COPY --chown=appuser:appuser . .

USER appuser

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
